Acorn/Account/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from django.views.generic import TemplateView

from .views import (
    account_register,
    account_activate,
    dashboard,
    orders,
    edit_details,
    delete_user,
    view_address,
    add_address,
    edit_address,
    delete_address,
    set_default,
    wishlist,
    add_to_wishlist,
)
from .forms import (
    UserLoginForm,
    PwdResetForm,
    PwdResetConfirmForm,
)

app_name = "account"

urlpatterns = [
    path('register/', account_register, name='register'),
    path('login/', 
         LoginView.as_view(
             template_name='account/login.html', 
             form_class=UserLoginForm
         ), 
         name='login'
    ),
    path('logout/', LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', account_activate, name='activate'),
    path('password_reset/', 
         PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url='password_reset_email_confirm',
            email_template_name='account/password_reset/password_reset_email.html',
            form_class=PwdResetForm
         ), 
         name='pwdreset'
    ),
    path('password_reset_confirm/<uidb64>/<token>', 
         PasswordResetConfirmView.as_view(
             template_name='account/password_reset/password_reset_confirm.html',
             success_url='/account/password_reset_complete/', 
             form_class=PwdResetConfirmForm),
         name="password_reset_confirm"
    ),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(
             template_name="account/password_reset/reset_status.html"
         ), 
         name='password_reset_done'
    ),
    path('password_reset_complete/',
         TemplateView.as_view(
             template_name="account/password_reset/reset_status.html"
         ), 
         name='password_reset_complete'
    ),

    # User dashboard
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/orders/', orders, name='orders'),
    path('profile/edit/', edit_details, name='edit_details'),
    path('profile/delete/', delete_user, name='delete_user'),
    path('profile/delete_confirm/', 
         TemplateView.as_view(
             template_name="account/dashboard/delete_confirm.html"
         ), name='delete_confirmation'
    ),
    path("addresses/", view_address, name="addresses"),
    path("add_address/", add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", edit_address, name="edit_address"),
    path("addresses/delete/", delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", set_default, name="set_default"),

    # Wish List
    path("wishlist", wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", add_to_wishlist, name="user_wishlist"),
]

Acorn/Acorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from DRF.views import ProductViewSet, ProductInventoryViewSet

from Search.views import SearchProductInventory


router = routers.DefaultRouter()
router.register(r'products', ProductViewSet, basename="products")
router.register(r'inventory/(?P<slug>[^/.]+)', ProductInventoryViewSet, basename="inventory")


urlpatterns = [
    path('', include("Demo.urls", namespace="demo")),
    path('cart/', include("Cart.urls", namespace="cart")),
    path('account/', include("Account.urls", namespace="account")),
    path('payment/', include("Payment.urls", namespace="payment")),
    path('orders/', include("Orders.urls", namespace="orders")),
    path('delivery/', include("Delivery.urls", namespace="delivery")),
    path('admin/', admin.site.urls),

    # API and SEO
    path('api/', include(router.urls)),
    path('search/<str:query>/', SearchProductInventory.as_view())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Acorn/Cart/urls.py
from django.urls import path

from .views import summary, update

app_name = "cart"

urlpatterns = [
    path('', summary, name="summary"),
    path('update/', update, name="update"),
]

Acorn/Demo/urls.py
from django.urls import path

from .views import (
    default_products,
    products_by_category,
    product_detail,
)

app_name = "demo"

urlpatterns = [
    path('', default_products, name="default_products"),
    path('product-by-category/<slug:category>/', products_by_category, name="products_by_category"),
    path('product-detail/<slug:slug>', product_detail, name="product_detail"),
]

Acorn/templates/products/detail.html
{% extends "base.html" %}

{% block title %}
    {{ product.product.name }}
{% endblock title %}

{% block content %}
    <main class="pt-5">
        <div class="container">
            {% if messages %}
                <div class="alert alert-warning" alert-"{{ message.tags }}" role="alert">
                    {% for message in messages  %}
                    {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">Your wishlist</a>.
                    {% endfor %}
                </div>
            {% endif %}
            <div class="row g-3">
                <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
                    <div class="d-grid gap-2">
                        <div class="d-flex d-flex-inline justify-content-between">
                            <div>
                                <span class="h3">£{{ product.store_price }}</span>
                                <p class="text-muted">includes tax</p>
                            </div>
                            <div>
                                <label for="select">Qty</label>
                                <select id="select" class="h6" style="width:50px;height:40px;">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                            </div>
                        </div>
                        <div class="d-flex d-flex-inline justify-content-between">
                            <p>{{ product.product.description|slice:":355" }}...</p>
                        </div>
                        <hr>
                        <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-success fw500">Add to cart</button>
                        {% if in_the_wishlist %}
                            <a role="button" href="{% url 'account:user_wishlist' product.id %}" class="btn btn-light fw500">Remove from wishlist</a>
                        {% else %}
                            {% if request.user.is_authenticated %}
                                <a role="button" href="{% url 'account:user_wishlist' product.id %}" class="btn btn-light fw500">Add to wishlist</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-7 col-lg-7 p-0">
                    <div class="card mb-3 border-0">
                        <div class="row g-0">
                            <div class="col-md-12">
                                <div class="card-body p-1">
                                    <h1 class="mb-0 h2 pe-4 pb-4">{{ product.product.name }}</h1>
                                    <div class="bg-light">
                                        <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.media_product_inventory.get.img_url.url }}"> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script>
        $(document).on('click', '#add-button', function(event) {
            event.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "cart:update" %}',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    product_id: $('#add-button').val(),
                    product_qty: $('#select option:selected').val(),
                    action: 'add',
                },
                success: function(json) {
                    document.getElementById("cart-qty").innerHTML = json.qty;
                },
                error: function(xhr, errmsg, err) {

                },
            });
        });
    </script>
{% endblock content %}

Acorn/templates/products/products_by_category.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Products
{% endblock title %}

{% block content %}
    <div class="album py-5">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for product in products %}   
                    <div class="col">
                        <div class="card shadow-sm rounded">
                            <img class="img-fluid" alt="{{ product.product.get.media_product_inventory.get.alt_text }}" src="{{ product.product.get.media_product_inventory.get.img_url.url }}">
                            <div class="card-body">
                                <p class="card-text text-decoration-none">
                                    {{ product.name }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a type="button" class="btn btn-sm btn-outline-primary" href="{% url 'demo:product_detail' product.slug %}">View</a>
                                    </div>
                                    <small class="text-muted">Price: £{{ product.product.get.store_price }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}