Acorn/Account/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from django.views.generic import TemplateView

from .views import (
    account_register,
    account_activate,
    dashboard,
    orders,
    edit_details,
    delete_user,
    view_address,
    add_address,
    edit_address,
    delete_address,
    set_default,
    wishlist,
    add_to_wishlist,
)
from .forms import (
    UserLoginForm,
    PwdResetForm,
    PwdResetConfirmForm,
)

app_name = "account"

urlpatterns = [
    path('register/', account_register, name='register'),
    path('login/', 
         LoginView.as_view(
             template_name='account/login.html', 
             form_class=UserLoginForm
         ), 
         name='login'
    ),
    path('logout/', LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', account_activate, name='activate'),
    path('password_reset/', 
         PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url='password_reset_email_confirm',
            email_template_name='account/password_reset/password_reset_email.html',
            form_class=PwdResetForm
         ), 
         name='pwdreset'
    ),
    path('password_reset_confirm/<uidb64>/<token>', 
         PasswordResetConfirmView.as_view(
             template_name='account/password_reset/password_reset_confirm.html',
             success_url='/account/password_reset_complete/', 
             form_class=PwdResetConfirmForm),
         name="password_reset_confirm"
    ),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(
             template_name="account/password_reset/reset_status.html"
         ), 
         name='password_reset_done'
    ),
    path('password_reset_complete/',
         TemplateView.as_view(
             template_name="account/password_reset/reset_status.html"
         ), 
         name='password_reset_complete'
    ),

    # User dashboard
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/orders/', orders, name='orders'),
    path('profile/edit/', edit_details, name='edit_details'),
    path('profile/delete/', delete_user, name='delete_user'),
    path('profile/delete_confirm/', 
         TemplateView.as_view(
             template_name="account/dashboard/delete_confirm.html"
         ), name='delete_confirmation'
    ),
    path("addresses/", view_address, name="addresses"),
    path("add_address/", add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", edit_address, name="edit_address"),
    path("addresses/delete/", delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", set_default, name="set_default"),

    # Wish List
    path("wishlist", wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", add_to_wishlist, name="user_wishlist"),
]

Acorn/Acorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from DRF.views import ProductViewSet, ProductInventoryViewSet

from Search.views import SearchProductInventory


router = routers.DefaultRouter()
router.register(r'products', ProductViewSet, basename="products")
router.register(r'inventory/(?P<slug>[^/.]+)', ProductInventoryViewSet, basename="inventory")


urlpatterns = [
    path('', include("Demo.urls", namespace="demo")),
    path('cart/', include("Cart.urls", namespace="cart")),
    path('account/', include("Account.urls", namespace="account")),
    path('payment/', include("Payment.urls", namespace="payment")),
    path('orders/', include("Orders.urls", namespace="orders")),
    path('delivery/', include("Delivery.urls", namespace="delivery")),
    path('admin/', admin.site.urls),

    # API and SEO
    path('api/', include(router.urls)),
    path('search/<str:query>/', SearchProductInventory.as_view())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Acorn/Cart/urls.py
from django.urls import path

from .views import summary, update

app_name = "cart"

urlpatterns = [
    path('', summary, name="summary"),
    path('update/', update, name="update"),
]

Acorn/templates/base.html
<!doctype html>

{% load static %}

{% load inventory %}

{% get_categories_list as categories %}

<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            {% block title %}
                Acorn
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

        <link href="{% static 'CSS/carousel.css' %}" rel="stylesheet">
        <link href="{% static 'CSS/cart.css' %}" rel="stylesheet">
        {% comment %} <link href="{% static 'CSS/base.css' %}" rel="stylesheet"> {% endcomment %}
    </head>
    <body class="d-flex flex-column min-vh-100">
        {% comment %} <header data-bs-theme="dark">
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark border-bottom border-secondary border-3">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">
                        Acorn
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item">
                                <a href="#sidebar" class="nav-link" role="button" data-bs-toggle="offcanvas" aria-controls="sidebar">
                                    Library
                                </a>  
                            </li>
                        </ul>
                        <a type="button" role="button" href="{% url 'cart:summary' %}" class="btn btn-outline-primary nav-item mx-2 ">
                            {% with total_qty=cart|length %}
                                <div id="cart-qty" class="d-inline-flex">
                                    {{ total_qty }}
                                </div>
                            {% endwith %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </svg>
                            Cart
                        </a>
                        
                    </div>
                </div>
            </nav>
        </header> {% endcomment %}
        <header class="pb-3">
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark border-bottom border-secondary border-3">
                <div class="container-fluid px-md-4">
                    <div class="d-flex w-100 navbar-collapse">
                        <a class="navbar-brand d-flex-inline" href="/">
                            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
                            </svg>
                        </a>
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item">
                                <a href="#sidebar" class="nav-link" role="button" data-bs-toggle="offcanvas" aria-controls="sidebar">
                                    Library
                                </a>  
                            </li>
                        </ul>
                        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                            aria-label="Toggle navigation">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                    class="bi bi-list" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </div>
                            <span class="fs15 fw500">Shop</span>
                        </button>
    
                        {% if user.is_authenticated %}
                            <a type="button" role="button" href="{% url 'account:logout' %}"
                                class="btn btn-outline-primary border-0 basket-btn">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                        class="bi bi-door-closed" viewBox="0 0 16 16">
                                        <path
                                            d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                        <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                                    </svg>
                                </div>
                                <span class="fs15 fw500">Logout</span>
                            </a>
                            <a type="button" role="button" href="{% url 'account:dashboard' %}"
                                class="btn btn-outline-primary border-0 basket-btn">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                        class="bi bi-person" viewBox="0 0 16 16">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                                    </svg>
                                </div>
                                <span class="fs15 fw500">Account</span>
                            </a>
                        {% else %}
                            <a type="button" role="button" href="{% url 'account:login' %}"
                                class="btn btn-outline-primary border-0 basket-btn">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                        class="bi bi-door-closed" viewBox="0 0 16 16">
                                        <path
                                            d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                        <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                                    </svg>
                                </div>
                                <span class="fs15 fw500">Login</span>
                            </a>
                        {% endif %}
    
    
                        <a type="button" role="button" href="{% url 'cart:summary' %}"
                            class="btn btn-outline-primary border-0 cart-btn">
                            {% with total_qty=cart|length %}
                                <div id="cart-qty" class="d-inline-flex cart-qty">
                                    {{ total_qty }}
                                </div>
                            {% endwith %}
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                    class="bi bi-cart3" viewBox="0 0 16 16">
                                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                </svg>
                            </div>
                            <span class="fs15 fw500">Cart</span>
                        </a>
                    </div>
                    <form class="d-flex w-100 d-md-none">
                        <input class="form-control me-2" type="search" placeholder="Search products or FAQ" aria-label="Search">
                        <button class="btn btn-outline-secondary" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </header>

        <!-- offcanvas -->

        <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="sidebar" aria-labelledby="sidebar-label">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="sidebar-label fw-bold">Categories:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <form class="d-flex mx-4 mb-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Enter</button>
            </form>
            <div class="offcanvas-body">
                {% include "includes/categories_list.html" %}
            </div>
        </div>


        {% block content %}
        {% endblock content %}

        <!-- FOOTER -->

        <footer class="container border border-secondary border-3 rounded mt-auto">
            <div class="mt-3">
                <p class="float-end">
                    <a href="#">Back to top</a>
                </p>
                <p>&copy; 2017–2023 Company, Inc. &middot; 
                    <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
                </p>
            </div>
        </footer>
    </body>
</html>