Acorn/Account/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from django.views.generic import TemplateView

from .views import (
    account_register,
    account_activate,
    dashboard,
    orders,
    edit_details,
    delete_user,
    view_address,
    add_address,
    edit_address,
    delete_address,
    set_default,
    wishlist,
    add_to_wishlist,
)
from .forms import (
    UserLoginForm,
    PwdResetForm,
    PwdResetConfirmForm,
)

app_name = "account"

urlpatterns = [
    path('register/', account_register, name='register'),
    path('login/', 
         LoginView.as_view(
             template_name='account/login.html', 
             form_class=UserLoginForm
         ), 
         name='login'
    ),
    path('logout/', LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', account_activate, name='activate'),
    path('password_reset/', 
         PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url='password_reset_email_confirm',
            email_template_name='account/password_reset/password_reset_email.html',
            form_class=PwdResetForm
         ), 
         name='pwdreset'
    ),
    path('password_reset_confirm/<uidb64>/<token>', 
         PasswordResetConfirmView.as_view(
             template_name='account/password_reset/password_reset_confirm.html',
             success_url='/account/password_reset_complete/', 
             form_class=PwdResetConfirmForm),
         name="password_reset_confirm"
    ),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(
             template_name="account/password_reset/reset_status.html"
         ), 
         name='password_reset_done'
    ),
    path('password_reset_complete/',
         TemplateView.as_view(
             template_name="account/password_reset/reset_status.html"
         ), 
         name='password_reset_complete'
    ),

    # User dashboard
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/orders/', orders, name='orders'),
    path('profile/edit/', edit_details, name='edit_details'),
    path('profile/delete/', delete_user, name='delete_user'),
    path('profile/delete_confirm/', 
         TemplateView.as_view(
             template_name="account/dashboard/delete_confirm.html"
         ), name='delete_confirmation'
    ),
    path("addresses/", view_address, name="addresses"),
    path("add_address/", add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", edit_address, name="edit_address"),
    path("addresses/delete/", delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", set_default, name="set_default"),

    # Wish List
    path("wishlist", wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", add_to_wishlist, name="user_wishlist"),
]

Acorn/Acorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from DRF.views import ProductViewSet, ProductInventoryViewSet

from Search.views import SearchProductInventory


router = routers.DefaultRouter()
router.register(r'products', ProductViewSet, basename="products")
router.register(r'inventory/(?P<slug>[^/.]+)', ProductInventoryViewSet, basename="inventory")


urlpatterns = [
    path('', include("Demo.urls", namespace="demo")),
    path('cart/', include("Cart.urls", namespace="cart")),
    path('account/', include("Account.urls", namespace="account")),
    path('payment/', include("Payment.urls", namespace="payment")),
    path('orders/', include("Orders.urls", namespace="orders")),
    path('delivery/', include("Delivery.urls", namespace="delivery")),
    path('admin/', admin.site.urls),

    # API and SEO
    path('api/', include(router.urls)),
    path('search/<str:query>/', SearchProductInventory.as_view())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Acorn/Cart/urls.py
from django.urls import path

from .views import summary, update

app_name = "cart"

urlpatterns = [
    path('', summary, name="summary"),
    path('update/', update, name="update"),
]

Acorn/Delivery/urls.py
from django.urls import path

from .views import (
    delivery_choices,
    cart_update_delivery,
    delivery_address,
    payment_selection,
)

app_name = "delivery"

urlpatterns = [
    path("delivery_choices/", delivery_choices, name="delivery_choices"),
    path("cart_update_delivery/", cart_update_delivery, name="cart_update_delivery"),
    path("delivery_address/", delivery_address, name="delivery_address"),
    path("payment_selection/", payment_selection, name="payment_selection"),
]

Acorn/Delivery/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _



class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    class Meta:
        verbose_name = _("Delivery option")
        verbose_name_plural = _("Delivery options")
        ordering = ("order",)


    DELIVERY_CHOICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(
        verbose_name=_("list order"), 
        help_text=_("Required"),
        default=0
    )
    is_active = models.BooleanField(
        default=True
    )


    def __str__(self):
        return self.delivery_name

Acorn/Delivery/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http.response import JsonResponse, HttpResponseRedirect

from .models import DeliveryOptions

from Cart.cart import Cart

from Account.models import UserAddress


@login_required
def delivery_choices(request):
    delivery_options = DeliveryOptions.objects.filter(is_active=True)
    return render(request, "delivery/delivery_choices.html", {"delivery_options": delivery_options})

@login_required
def cart_update_delivery(request):
    cart = Cart(request)

    if request.POST.get("action") == "post":
        delivery_option = request.POST.get("delivery_option")
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = cart.cart_update_delivery(float(delivery_type.delivery_price))

        session = request.session

        if "purchase" not in request.session:
            session["purchase"] = {
                "delivery_id": delivery_type.id,
            }
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True

        return JsonResponse({"total": updated_total_price, 
                             "delivery_price": delivery_type.delivery_price, 
                             "delivery_name": delivery_type.delivery_name})
    
@login_required
def delivery_address(request):
    session = request.session

    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    addresses = UserAddress.objects.filter(user=request.user).order_by("-is_main")

    if not addresses:
        return redirect('account:add_address')

    if "address" not in request.session:
        session["address"] = {"address_id": str(addresses[0].id)}
    else:
        session["address"]["address_id"] = str(addresses[0].id)
        session.modified = True

    return render(request, "delivery/delivery_address.html", {"addresses": addresses})

@login_required
def payment_selection(request):

    if "address" not in request.session:
        messages.success(request, "Please select address option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    return render(request, "delivery/payment_selection.html")

Acorn/templates/delivery/delivery_address.html
{% extends "base.html" %}

{% block title %}
    Basket Summary
{%endblock %}

{% block content %}
    <main class="pt-5">
        <div class="container">
            <div class="col-12">
                <h1 class="h2">Delivery Address</h1>
            </div>
            <div class="col-12">
                <p>Please select your delivery address</p>
            </div>
            <hr />
        </div>

        <div class="container">
            <div class="row g-3">
                {% if addresses|length == 0 %}
                    <div class="col-12">
                        There are no delivery addresses, 
                        <a href="{% url 'account:add_address' %}">
                            add address
                        </a>
                    </div>
                {% else %}
                    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                        <div class="d-flex bd-highlight ms-0">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                Sub Total:
                            </div>
                            <div class="p-2 bd-highlight">
                                <span class="fw-bold h5">£</span>
                                <span id="sub_total"class="fw-bold h5">
                                    {{ cart.get_subtotal_price }}
                                </span>
                            </div>
                        </div>
                        <div class="d-flex bd-highlight">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                Delivery Cost:
                            </div>
                            <div class="p-2 bd-highlight">
                                <span class="fw-bold h5">£</span>
                                <span id="delivery_price" class="fw-bold h5">
                                    {{ cart.get_delivery_price }}
                                </span>
                            </div>
                        </div>
                        <div class="d-flex bd-highlight">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                Total:
                            </div>
                            <div class="p-2 bd-highlight">
                                <span class="fw-bold h5">£</span>
                                <span id="total"class="fw-bold h5">
                                    {{ cart.get_total_price }}
                                </span>
                            </div>
                        </div>
                        <a role="button" href="{% url 'payment:cart' %}" class="btn btn-success fw-bold w-100" type="button">
                            Pay Securely
                        </a>
                    </div>
                    <div class="col-md-7 col-lg-8">
                        {% for address in addresses %}
                            {% if not address.is_main %}
                                <h1 class="h5 pt-4">Other Addresses</h1>
                            {% endif %}
                            <div class="card mb-3 border-1 product-item me-md-4" data-index="{{ option.id }}">
                                <div class="row g-0">
                                    <div class="col">
                                        <div class="card pb-3">
                                            <div class="card-header small text-muted">
                                                {% if address.is_main %}
                                                    Selected
                                                {% else %}
                                                    Additional address
                                                {% endif %}
                                                &nbsp;
                                            </div>
                                            <div class="card-body small pb-1">
                                                <p class="card-text m-0 fw-bold">Country: {{ address.country }}</p>
                                                <p class="card-text m-0">City: {{ address.city }}</p>
                                                <p class="card-text m-0">Postal code: {{ address.postal_code }}</p>
                                                <p class="card-text m-0">Address: {{ address.address_line_1 }}</p>
                                                {% if address.address_line_2 %}
                                                    <p class="card-text m-0">{{ address.address_line_2 }}</p>
                                                {% endif %}
                                                <p class="card-text m-0">Phone number: {{ address.phone_number_1 }}</p>
                                                <div class="pt-5">
                                                    <a href="{% url 'account:edit_address' address.id %}" class="text-decoration-none">Edit</a>
                                                    {% if not address.is_main %}
                                                    | <a href="{% url 'account:set_default' address.id %}" class="text-decoration-none">Select</a>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

Acorn/templates/delivery/delivery_choices.html
{% extends "base.html" %}

{% block title %}
    Delivery Options
{% endblock %}

{% block content %}
    <main class="pt-5">
        <div class="container">
            <div class="col-12">
                <h1 class="h2">Delivery Options</h1>
            </div>
            <div class="col-12">
                <p>Select your delivery options</p>
            </div>
            <hr />
        </div>

        <div class="container">
            {% if messages %}
                <div class="alert alert-warning" alert-{{ message.tags }} role="alert">
                    {% for message in messages  %}
                        {{ message|safe }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="row g-3">
                {% if delivery_options|length == 0 %}
                    <div class="col-12">
                        There are no delivery options 
                        <a href="/">
                            Shop
                        </a>
                    </div>
                {% else %}
                    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                        <div class="d-flex bd-highlight ms-0">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                Sub Total:
                            </div>
                            <div class="p-2 bd-highlight">
                                <span class="fw-bold h5">£</span>
                                <span id="sub_total" class="fw-bold h5">{{ cart.get_subtotal_price }}</span>
                            </div>
                        </div>
                        <div class="d-flex bd-highlight">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                Delivery Cost:
                            </div>
                            <div class="p-2 bd-highlight">
                                <span class="fw-bold h5">£</span>
                                <span id="delivery_price" class="fw-bold h5">{{ cart.get_delivery_price }}</span>
                            </div>
                        </div>
                        <div class="d-flex bd-highlight">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                Total
                            </div>
                            <div class="p-2 bd-highlight">
                                <span class="fw-bold h5">£ </span><span id="total" class="fw-bold h5">{{ cart.get_total_price }}</span>
                            </div>
                        </div>
                        <a role="button" href="{% url "delivery:delivery_address" %}" class="btn btn-success fw-bold w-100" type="button">
                            Pay Securely
                        </a>
                    </div>
                    <div class="col-md-7 col-lg-8">
                        {% for option in delivery_options %}
                            <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{ option.id }}">
                                <div class="row g-0">
                                    <div class="col-md-2 ps-3 ps-md-4">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2" viewBox="0 0 16 16">
                                            <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                                        </svg>
                                    </div>
                                    <div class="col-md-9 ps-md-1">
                                        <div class="card-body p-1">
                                            <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{ option.delivery_name }}</p>
                                            <p class="card-text ps-2 pb-3">Your order should be delivered within {{ option.delivery_timeframe }}</p>
                                        </div>
                                    </div>
                                    <div class="col-md-1 ps-md-1">
                                        <input class="align-middle h-100" type="radio" name="deliveryOption" id="{{ option.id }}" value="{{ option.id }}">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </main>

    <script>
        $('input[type=radio][name=deliveryOption]').on('change', function(event) {
            event.preventDefault();
            $.ajax({
                type: "POST",
                url: '{% url "delivery:cart_update_delivery" %}',
                data: {
                    delivery_option: $(this).val(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: "post",
                },
                success: function (json) {
                    document.getElementById("total").innerHTML = json.total;
                    document.getElementById("delivery_price").innerHTML = json.delivery_price;
                },
                error: function (xhr, errmsg, err) {
                    console.error(err)
                },
            });
            
        });
    </script>
    
{% endblock %}

Acorn/templates/delivery/payment_selection.html
{% extends "base.html" %}

{% block title %}
    Payment selection
{%endblock %}

{% block content %}
    <main class="pt-5">
        <div class="container">
            <div class="col-12">
                <h1 class="h2">Delivery Options</h1>
            </div>
            <div class="col-12">
                <p>Please select your delivery option</p>
            </div>
            <hr />
        </div>

        <div class="container">
            <div class="row g-3">
                <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                    <div class="d-flex bd-highlight ms-0">
                        <div class="p-2 flex-grow-1 bd-highlight">
                            Sub Total:
                        </div>
                        <div class="p-2 bd-highlight">
                            <span class="fw-bold h5">£</span>
                            <span id="sub_total" class="fw-bold h5">
                                {{ cart.get_subtotal_price }}
                            </span>
                        </div>
                    </div>
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">
                            Delivery Cost:
                        </div>
                        <div class="p-2 bd-highlight">
                            <span class="fw-bold h5">£</span>
                            <span id="delivery_price" class="fw-bold h5">
                                {{ cart.get_delivery_price }}
                            </span>
                        </div>
                    </div>
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">
                            Total:
                        </div>
                        <div class="p-2 bd-highlight">
                            <span class="fw-bold h5">£</span>
                            <span id="total" class="fw-bold h5">
                                {{ cart.get_total_price }}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
                    <div id="paypal-button-container">
                        <!-- Payment elements will appear here -->
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}